# Generated by Django 4.2.23 on 2026-02-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpillar',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
