# Generated by Django 4.2.28 on 2026-02-06 11:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadinessScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_level', models.CharField(choices=[('startup', 'Startup'), ('corporate', 'Corporate'), ('leading', 'Leading')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('verified_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('unverified_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pillar_breakdown', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_scores', to='jobs.jobrole')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_scores', to='profiles.studentprofile')),
            ],
            options={
                'unique_together': {('profile', 'job_role', 'company_level')},
            },
        ),
    ]
